# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - doxygen
    - graphviz
  # Ubuntu 22.04 has KiCad 6.0, which does not have kicad-cli.
  # We'll have to keep this commented (and generate PDFs manually with `make gen`) until ReadTheDocs adds Ubuntu 24.04.
  # apt_packages:
  #   - kicad
  # jobs:
  #   pre_install:
  #     - bash -c "mkdir -p ~/.config/kicad/7.0/colors && cp ./docs/assets/kicad/colors/Dark.json ~/.config/kicad/7.0/colors/Dark.json"
  #     - make -C docs gen
  jobs:
    pre_install:
      - make -C docs doxygen

sphinx:
  configuration: docs/conf.py
  builder: dirhtml

formats:
   - pdf

python:
   install:
   - requirements: docs/requirements.txt
