#ifndef _HW_CONFIG_H_
#define _HW_CONFIG_H_

#define HW_CONTROLLER_GPIO_UP 4
#define HW_CONTROLLER_GPIO_DOWN 7
#define HW_CONTROLLER_GPIO_LEFT 5
#define HW_CONTROLLER_GPIO_RIGHT 6
#define HW_CONTROLLER_GPIO_SELECT 9
#define HW_CONTROLLER_GPIO_START 10
#define HW_CONTROLLER_GPIO_A 20
// #define HW_CONTROLLER_GPIO_B 21
#define HW_CONTROLLER_GPIO_B -1

#endif /* _HW_CONFIG_H_ */
